// <auto-generated />
using System;
using DomainServices;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DomainServices.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DomainModel.Model.Kategorijaopreme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("kategorijaopreme");
                });

            modelBuilder.Entity("DomainModel.Model.Oprema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("Datumkupnje")
                        .HasColumnType("date");

                    b.Property<int?>("FkKategorijaid")
                        .HasColumnType("integer");

                    b.Property<int?>("FkPrethodnivlasnikid")
                        .HasColumnType("integer");

                    b.Property<int?>("FkStatusid")
                        .HasColumnType("integer");

                    b.Property<int?>("FkTrenutnivlasnikid")
                        .HasColumnType("integer");

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .HasColumnType("text");

                    b.Property<string>("Serijskibroj")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("oprema");
                });

            modelBuilder.Entity("DomainModel.Model.Osoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Datumrodenja")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Datumzaposljenja")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int?>("FkPozicijaid")
                        .HasColumnType("integer");

                    b.Property<int?>("FkTimid")
                        .HasColumnType("integer");

                    b.Property<int?>("FkUlogaid")
                        .HasColumnType("integer");

                    b.Property<string>("Ime")
                        .HasColumnType("text");

                    b.Property<bool?>("Jezaposlen")
                        .HasColumnType("boolean");

                    b.Property<string>("Kontaktbr")
                        .HasColumnType("text");

                    b.Property<string>("Lozinka")
                        .HasColumnType("text");

                    b.Property<string>("Oib")
                        .HasColumnType("text");

                    b.Property<string>("Prezime")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("osoba");
                });

            modelBuilder.Entity("DomainModel.Model.Pozicija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("pozicija");
                });

            modelBuilder.Entity("DomainModel.Model.Statusopreme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("statusopreme");
                });

            modelBuilder.Entity("DomainModel.Model.Tim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tim");
                });

            modelBuilder.Entity("DomainModel.Model.Uloga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("uloga");
                });
#pragma warning restore 612, 618
        }
    }
}
